### PR TITLE
escape character

### PR DESCRIPTION
**Pull request by shumin1027**
#2 invalid json format err when the shell script contain “”

### CODE REVIEW

**Review by adamsla — CHANGES_REQUESTED** [review]
Can you please update the pull request to utilize hard tabs instead of soft?  That would be appreciated.  I'm just comparing to the rest of the code and it looks like the coding standard is hard tabs.

**Comment by adamsla** [comment]
Also, can you please sign off per the DCO.

**Comment by shumin1027** [comment]
> Can you please update the pull request to utilize hard tabs instead of soft? That would be appreciated. I'm just comparing to the rest of the code and it looks like the coding standard is hard tabs.

thanks, I will amend it

**Comment by adamsla** [comment]
@shumin1027, you need to sign of using your real email address like:

Signed Off: adamsla@us.ibm.com

Just read the DCO instructions in the base of the repo before signing off.

**Comment by shumin1027** [comment]
> @shumin1027, you need to sign of using your real email address like:
> 
> Signed Off: [adamsla@us.ibm.com](mailto:adamsla@us.ibm.com)
> 
> Just read the DCO instructions in the base of the repo before signing off.

```Signed Off: shumin1027@gmail.com```

**Review by adamsla — APPROVED** [review]

**Comment by adamsla** [comment]
Thanks for your patience.

**Pull request merged**
